name: Build preview apk

on:
  push:
    branches:
      - master

jobs:
  update:
    name: Build preview apk
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "EXPO_TOKEN secret not found!"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run EAS build
        run: BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }} eas build --profile preview --platform android --local
        env:
          BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: PagePatrol.apk
          path: ./*.apk
